server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: '#{60 * 5 * 1000}'